[block]
model = "tJ"
n_sites = 10

[files]
save_file = "/Users/lstaszewski/Research/Projects/julia-ed/jobs/waiting/2023-03-28.test/data/data_0.h5"

[misc]
n_jobs = 1
job_name = "2023-03-28.test"
date = 2023-03-28
