[hamiltonian]
t1 = 10
t2 = 2.5

[files]
save_file = "/Users/lstaszewski/Research/Projects/template_project_folder/jobs/waiting/2023-03-28.test/data/data_1.h5"

[misc]
n_jobs = 5
job_name = "2023-03-28.test"
date = 2023-03-28
